#version: '3.8'

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    # ports:
    # - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d peluqueria_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c timezone=America/Argentina/Buenos_Aires

  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro

volumes:
  postgres_data: 
