version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: peluqueria_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    # - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d peluqueria_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c timezone=America/Argentina/Buenos_Aires

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=peluqueria_db
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=clave_segura_default
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  postgres_data: 
